### ISSUE TITLE
On linux with jack, delay occurs.

### ISSUE THREAD

**Issue by BeatsMe** [jjazzboss/JJazzLab-X#145]
Hi,
I'm using https://www.jjazzlab.com/pkg/JJazzLab-2.2.0-Linux.zip .
As I mentioned on the title, there's some unbearable delay on sound and the cursor position
when I use JJazzLab with Jack on my Manjaro Linux.

I think previous version had no problem with Jack, though it has not been verified 
because of lack of the previous version.

I want to use Jack and JJazzLab at the same time to have fun with Guitarix, a effector simulator.
Please have JJazzLab to compatibility with Jack audio connection kit.

Best regards.

**Comment by jjazzboss** [comment]
JJazzLab only sends Midi data: delay is introduced by the audio device you connect to the output of JJazzLab. JJazzLab can't do anything about that. Did you try with FluidSynth using virtual Midi port as explained here https://www.jjazzlab.com/en/doc/fluidsynth/.   I use an old Linux (Mint) laptop and I don't experience noticeable delay with this configuration.

**Comment by BeatsMe** [comment]
Thank you for your reply.
There's no delay on JJazzlab with the procedures you taught me.
Thank you.
