### ISSUE TITLE
Add feature usage analytics

### ISSUE THREAD

**Issue by jjazzboss** [jjazzboss/JJazzLab-X#177]
In order to know which features are used the most, etc.

**Comment by nukeop** [comment]
How can I disable this phone home feature?

**Comment by jjazzboss** [comment]
Users can easily disable it in menu Tools/Options/Advanced. It's also mentionned in the licence agreement.

**Comment by nukeop** [comment]
How about making it opt in instead of being enabled by default without clearly communicating it? Nobody reads licence agreements and everyone knows it.
