### ISSUE TITLE
Add keyboard shortcuts to make playback jump to the next song part (or previous one)

### ISSUE THREAD

**Issue by jjazzboss** [jjazzboss/JJazzLab-X#193]

**Comment by bdutta** [comment]
Keyboard shortcuts, or even a menu option for new section would be great as well, as would be keyboard shortcuts for other actions on the various panes section editor, song editor etc. would be great.

**Comment by jjazzboss** [comment]
@bdutta you need to be more precise. What keyboard shortcuts are you missing ? Pressing Enter already opens the selected bar editor dialog where you can add a section. See also here [https://jjazzlab.gitbook.io/user-guide/songs/song-editors/chord-lead-sheet#keyboard-shortcuts](https://jjazzlab.gitbook.io/user-guide/songs/song-editors/chord-lead-sheet#keyboard-shortcuts)
