### ISSUE TITLE
Transpose chord symbols (not playback)

### ISSUE THREAD

**Issue by iwoithe** [jjazzboss/JJazzLab-X#202]
Hi there,

While playing instruments which are not in concert pitch (like saxophone), I find myself needing to be able to transpose the chord symbols more often than transposing the playback of the chords.

Thanks

**Comment by jjazzboss** [comment]
https://jjazzlab.gitbook.io/user-guide/faq#how-to-transpose-song

**Comment by iwoithe** [comment]
Thanks for the answer. However, often I want to flick between concert pitch and (in this case) an Eb instrument quickly. Selecting all chord symbols and then transposing them (in this case down a minor third) and then clicking on the transpose button so the chords still play in the original key takes a little to long for my liking.

**Comment by jjazzboss** [comment]
Not sure I understand. What is your request exactly ? 

Also, have you used the playback transpose function ? (the button with the sax icon)  You can enable/disable it in 2 clicks...

**Comment by iwoithe** [comment]
>  You can enable/disable it in 2 clicks

Yes, but than I have to transpose all of the chord symbols up again (to concert pitch).

Basically, I'd like an easier way to do this (e.g. do it in 1 step as appose to 2+ steps).

**Comment by jjazzboss** [comment]
You can use the mousewheel to transpose selected chords.
