### ISSUE TITLE
Linux: Submitting JJazzLab-X to the Arch User Repository

### ISSUE THREAD

**Issue by jypma** [jjazzboss/JJazzLab-X#203]
For easier installation, and to keep track of files, I've created a little `PKGBUILD` that helps download and install JJazzLab-X on Arch Linux. It's fairly trivial to do, and makes installing it easier (plus, it creates a nice menu entry for starting the application).

PKGBUILD:
```
# Maintainer: Jan Ypma <jan at ypmania dot nl>
pkgname=jjazzlab-x-bin
pkgver=2.3.1
pkgrel=1
pkgdesc="A Midi-based framework dedicated to backing tracks generation"
arch=('i686' 'x86_64')
url="https://www.jjazzlab.com/"
license=('LGPL')
depends=('java-environment>=8')
source=("https://www.jjazzlab.com/pkg/JJazzLab-${pkgver}-Linux.zip" "jjazzlab-x.desktop")
sha256sums=('f78c2c4721dbf93b766fe78b4e170c27760401a8a89d8f110b4f853cbd1f65be'
            'ca15408fd0f11505def63f04359bc3c9745c0077a9f3b5953edc31391ee7a882')

package() {
  cd "$srcdir/JJazzLab-${pkgver}-Linux"

  install -d "${pkgdir}/opt/jjazzlab-x"
  cp -rp * "${pkgdir}/opt/jjazzlab-x"

  install -d "${pkgdir}/usr/bin"
  ln -s ${pkgdir}/opt/jjazzlab-x/bin/jjazzlab ${pkgdir}/usr/bin/jjazzlab

  install -d "${pkgdir}/usr/share/applications"
  install ../jjazzlab-x.desktop "${pkgdir}/usr/share/applications"
}
```

jjazzlab-x.desktop:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=JJazzLab-X
Comment=A Midi-based framework dedicated to backing tracks generation
Exec=jjazzlab
Terminal=false
StartupNotify=true
Categories=Audio;Sequencer;Midi;AudioVideoEditing;Music;AudioVideo;
```

Would this be OK to submit to the [Arch Linux User Repository](https://wiki.archlinux.org/title/AUR_submission_guidelines) ?

**Comment by jjazzboss** [comment]
Yes, thanks !

**Comment by jypma** [comment]
Here it is: https://aur.archlinux.org/packages/jjazzlab-x-bin/ :)

If you want, you can link to it from your "Linux" installation instructions (I expect it'd be valid for Arch and Manjaro Linux).

**Comment by jjazzboss** [comment]
Great thanks again. I've updated the instructions: https://jjazzlab.gitbook.io/user-guide/installation#linux-instructions

**Comment by jjazzboss** [comment]
Hi, now that JJazzLab 4 is out, could you please help update the package ? It must use the bundled JRE. The only required dependency is FluidSynth >= 2.1
