### ISSUE TITLE
Enhancement to add Yamaha XG on Windows

### ISSUE THREAD

**Issue by bdutta** [jjazzboss/JJazzLab-X#217]
Wondering if an enhancement might be possible and meaningful to support Yamaha XG virtual instruments on Windows, using the method described [here](http://www.xg-central.com/playback-xg-midi-files-on-windows.php) (or any other method) ? However, I am not entirely sure if it'd result in the generated sounds being more pleasing to ears than say the remapped GM that then uses good quality samples.

**Comment by jjazzboss** [comment]
This means adding VST host capability, which would be great, but it's a huge work. In the mean time you can already use a virtual midi port and you can drive any VST host and its plugin. This way I've tried a long time ago this Yamaha XG VST, but I don't remember it was that good...
