### ISSUE TITLE
Ilegal reflective access operation

### ISSUE THREAD

**Issue by luchoArg33** [jjazzboss/JJazzLab-X#223]
Hi, when I run JjazzLab the app retrieves this error:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/luisarizaga/Documentos/Guitarra/JazzLab/Jazzlab/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
I'm using Fedora 33. App version is 2.3.1
App's great by the way. Thanks a lot =) 
Cheers,
Luis

**Comment by jjazzboss** [comment]
Yes, it's a "normal" Java warning, it can be safely ignored.
