### ISSUE TITLE
import .STY error

### ISSUE THREAD

**Issue by brusand** [jjazzboss/JJazzLab-X#225]
hi,

i can t import my .STY, decoding error like django.Sty
[Styles.zip](https://github.com/jjazzboss/JJazzLab-X/files/7447481/Styles.zip)

it is to output to sforzando free player
thx
Bruno

**Comment by jjazzboss** [comment]
I checked django.sty, it's not a valid Midi file, it does not start with the string "MThd". Where did the file come from ?
