### ISSUE TITLE
Hangs on startup and accessing tools menu on Linux

### ISSUE THREAD

**Issue by brau19** [jjazzboss/JJazzLab-X#245]
Once startup script begins and after (Loading cached objects ...Done) it hangs for about 2 minutes then loads.

Accessing the Tools -> Options menu it hangs again for about a minute and a half to 2 minutes
[jjazzlab_error.pdf](https://github.com/jjazzboss/JJazzLab-X/files/7746183/jjazzlab_error.pdf)

Brau

**Comment by jjazzboss** [comment]
I can't access your pdf file... I need the log file.

**Comment by brau19** [comment]
Desole Jerome - voila

est-il posiboe faire donacion via paypal?
Merci
 brau

**Comment by jjazzboss** [comment]
Yes you can, go to the JJazzLab website, donate page.
Jerome 

Envoyé de mon iPhone

**Comment by brau19** [comment]
Saw the link, and donated via my other emal - chebon

Merci

**Comment by jjazzboss** [comment]
I saw the pdf file but there is no error in the log... Is the problem still there?

**Comment by jypma** [comment]
I have the same issue. I'm on arch linux, clean install of 3.0.2a, removed my preferences. Startup hangs on the "Caching objects..." screen for a full 2 minutes, not using any CPU time (nor network, it seems). What is it supposed to be doing on startup?

**Comment by jjazzboss** [comment]
I would need your exact config (OS, version etc.) : best is to send the beginning of the log file.

I don't know what is this "Caching objects..." : it's performed by the underlying Netbeans platform framework, not by JJazzLab itself.

**Comment by jjazzboss** [comment]
Can you try with the new 3.1.0 release ? I upgraded to the latest Java JDK 17.

**Comment by jjazzboss** [comment]
No answer, I assume it's closed with the use of JDK17... I'll reopen if you guys tell me

**Comment by brau19** [comment]
Jerome,

I installed and ran 3.1 yesterday.

Initially had some issues with delays in using the menus but that went away
quickly.

Startup still hangs but, I think it is just an issue with my setup, not the
program.  It is just loading and it  ay be issues with my security setup.

I notice that some users are having issues with MIDI setup so I am planning
on recording the process on a clean install to see if that helps.

Brau
