### ISSUE TITLE
Add a builtin Midi phrase editor

### ISSUE THREAD

**Issue by hajdam** [jjazzboss/JJazzLab-X#263]
If you maybe would like to include some MIDI player, there is an example of basic one written in Java:

https://mac.softpedia.com/get/Audio/MidiSwing.shtml

It was freeware with promise of open source, but I assume author passed away, but I believe it could be tweaked for some basic use...

I mean there is also Frinika, but it's somewhat bigger beast...

Best regards,
HajdaM

**Comment by jjazzboss** [comment]
I don't see the need, what use-case do you have in mind?

**Comment by hajdam** [comment]
> I don't see the need for a player to play external Midi files... What use-case do you have in mind?

It's more like an editor - I thought because there's option to use external editor, that it might be useful to include directly some basic one or allow direct editing of styles with it, but never mind then...

**Comment by jjazzboss** [comment]
Ah you mean a piano-roll editor ? Yes that would be good to have such graphical component to edit a SizedPhrase. Do you want to do it ?   As a starting point you could have a look at this component: https://github.com/jjazzboss/JJazzLab-X/blob/master/Phrase/src/org/jjazz/phrase/api/ui/PhraseBirdsEyeView.java

**Comment by jjazzboss** [comment]
Implemented
