### ISSUE TITLE
Compile from Source no rythms

### ISSUE THREAD

**Issue by fr3sh** [jjazzboss/JJazzLab-X#282]
When I try to compile there is no rythm at all and when you try to add nothing happend. Only the dummy rythm :(

![image](https://user-images.githubusercontent.com/6498987/155387747-15124004-18ea-4604-a882-1a26bfde1ffa.png)

**Comment by jjazzboss** [comment]
This is normal, the YamJJazz rhythm provider you find in the JJazzLab distribution is not open-sourced yet.

**Comment by fr3sh** [comment]
:(
