### ISSUE TITLE
"OK to close this song without saving changes ?" prompt even if no song change happened

### ISSUE THREAD

**Issue by bengan** [jjazzboss/JJazzLab-X#284]
OS: Linux, openSUSE Tumbleweed
JJazzLab: 3.0.3

I always get "OK to close this song without saving changes ?" when I close a song. Even if no changes has happened.

Recreate:
1. Create a new song
2. Save it
3. Open it again and do nothing
4. Close the song

**Comment by jjazzboss** [comment]
You're right, can reproduce, I'll check this thanks
