### ISSUE TITLE
Live performance

### ISSUE THREAD

**Issue by IonicaBizau** [jjazzboss/JJazzLab-X#318]
Hi! 

Thank you so much for this amazing project!
What I am missing most from these applications is the ability to play a phyisical MIDI controller (e.g. a digital piano, or just an external MIDI keyboard) and playing the chords with the left hand and solo with the right hand.

Is this possible with JJazzLab-X? 
I installed the app and played a little bit with it but can't find such a feature.

Thanks! 🎹 🎶

**Comment by jjazzboss** [comment]
Yes it's possible: menu Window/Arranger keyboard mode

This feature is more for educational purpose,  it's not a true realtime arranger software and never will be. You can find other software on the web that can do this.

**Comment by IonicaBizau** [comment]
@jjazzboss Oh, that's amazing! Thanks for this! If there is another software you'd suggest for this please let me know, I have been searching for quite a while and did not find anything good so far.
