### ISSUE TITLE
Playing backing track in real time using MIDI input?

### ISSUE THREAD

**Issue by WuTianming** [jjazzboss/JJazzLab-X#334]
I remember those Yamaha keyboards had such a function where you can hold down a chord in the left hand, and then the keyboard will immediately play auto accompaniment track to that chord. This is a very handy feature for live playing, however I have searched the Internet and hadn't found a decent free software to do the exact same thing.

I wonder if this feature can be implemented within the framework of JJazzLab? It would be a great additional feature.

Also I'm tempted to fork JJazzLab and see what I can do with the code...

**Comment by jjazzboss** [comment]
Actually it's already there ! 
[https://jjazzlab.gitbook.io/user-guide/tools/arranger-keyboard-mode](https://jjazzlab.gitbook.io/user-guide/tools/arranger-keyboard-mode)

**Comment by WuTianming** [comment]
Wow, impressive! I'm gonna check it out right now.

However I see that there may be a delay due to the software. I will first try it, then decide if that bit of delay is too much for live performance (in which case I hope to improve it further to reduce the delay somehow).

great work ;-)

**Comment by WuTianming** [comment]
The delay seems acceptable for me xD
