### ISSUE TITLE
Broken code in master branch:  missing method and missing directories during build 

### ISSUE THREAD

**Issue by pedrorozo** [jjazzboss/JJazzLab-X#352]
Hi Jerome 

My name is Pedro, software/java architect and music composer, I anmv ery interested to play with jjazzlab and perhaps contribute with some ideas and code in the shorter future, after reading your documents for developers I downloaded the git repo (master branch) this morning, and worked with Netbeans 17 and jdk 11 (also testes with jdk17 with same results)  but during the build i found some issues ... I disabled one of them (comment the code), and the others were not blocker, but still i guess they can affect the build so here they are:

#1  (warnings) #1 Build of a lot of modules/subprojects fail because  the test folder does not exists for them ( I already double checked) , here an example:  

org.jjazz.outputsynth.build-init:
No such dir J:\datos\dev\NetBeansProjects17\JJazzLab-X\OutputSynth\test\unit\src; should not define test deps

#2 (blocker )  
J:\datos\dev\NetBeansProjects17\JJazzLab-X\SongEditorManager\src\org\jjazz\songeditormanager\LinearizeSong.java:73: error: cannot find symbol
        Song newSong = SongUtilities.getDeveloppedSong(song, true);
  symbol:   method getDeveloppedSong(Song,boolean)
  location: class SongUtilities

PR: I already check and that method does not exists  in that class just in case ..I disable those lines of code, i was able to finish the build and run the program . and i also notiece I was not able to open many styles that I open with the regular version  . so not sure if they are related ....

**Comment by jjazzboss** [comment]
Hi Pedro, please wait a few days, I'll put the master branch in a cleaner state so you can work. Up to now I was on my own so I commited directly to master, sometimes even non-compilable code -I know it's not good practice, but it was not a problem as long as I was th eonly one... ;-)

**Comment by pedrorozo** [comment]
No problem . just let me know once the code is ready and I wil jump to play
and experiment .. thanks

Regards/Cordial Saludo



*Pedro Rozo*

*Mobile: (+57) 312.300.6700  *

Bogotá D.C., Colombia.

**Comment by jjazzboss** [comment]
The master branch is now working for me (though not heavily tested...). I'm still actively developing version 4.0 but I'll push the latest changes on a dev branch.

**Comment by jjazzboss** [comment]
if you have questions don't hesitate
