### ISSUE TITLE
Many missing apostrophes

### ISSUE THREAD

**Issue by maximebochon** [jjazzboss/JJazzLab-X#353]
Version: JJazzLab 3.2.1
OS: Linux 5.15 / Ubuntu Studio 20.04.5 LTS

Many missing apostrophes were discovered in the French version of the "How to improvise" explanation (underlined in red in the screenshot):

![image](https://user-images.githubusercontent.com/7842269/227793793-93311316-dde1-41bb-802d-0de7c0909851.png)

I didn't do any other tests.

**Comment by jjazzboss** [comment]
Translations are not managed here, but in crowdin. Users can directly fix translations, please see [https://jjazzlab.gitbook.io/user-guide/contribute/translate-jjazzlab](https://jjazzlab.gitbook.io/user-guide/contribute/translate-jjazzlab).
