### ISSUE TITLE
Feature request: allow previewing styles in Rhythm selection dialog

### ISSUE THREAD

**Issue by weitzhandler** [jjazzboss/JJazzLab-X#54]
Hi,

First of all thanks to everybody taking part in this magnificent project! 🙏🏻

When trying to select a rhythm using the Rhythm selection dialog, it would make it tremendously easier if we could preview the various rhythm in the dialog to help us decide what to use.

Please add a small play button to each row.

![image](https://user-images.githubusercontent.com/2716316/79581896-bae13e80-80d3-11ea-8bbf-c96f76f0f029.png)

Thank you.

**Comment by jjazzboss** [comment]
Thanks for submitting the request ! Yes, it's really a needed feature... I'll try to work on it in the next releases.
