### ISSUE TITLE
Vizualisation/edition of user-recorded music

### ISSUE THREAD

**Issue by jjazzboss** [jjazzboss/JJazzLab-X#8]
Once user-recording features are enabled (see Issue #6 and Issue #7), how to visualize/edit the user-recorded music ? 

Objective is to enable **simple** visualization/edition capabilities of recorded music, plus quantization capabilities. For example with a piano-roll editor or, even simpler, automated export/import via an external Midi editor tool like MidiEditor.

**Comment by michaelsjackson** [comment]
I am a Reaper user, just discovered JJazzlab via Reaper forum, gratulations for this great software and sharing it. Wanted to suggest here, no need to add any editing, recording capabilities directly into jjazzlab.

I would see jjazzlab as a frontend tool, needing a backend, like the great or best Reaper DAW (in my opinion). Just route through a virtual midi port your midi data directly to Reaper, in linux via Catia for example and mix there!  All musical compositional work, can happen nicely inside jjazzlab, all sound/mixing/recording/editing can happen inside Reaper DAW.  Reaper allows track templates (also project templates and item templates), so you could design various templates fitting to your needs.

No need trying to replicate Reaper functionality inside jjazzlab, if you can just use the best tool directly, Reaper.  Wanted to suggest to you, in the hope you can save yourself time, having fun with music instead.  In case you need any help, I can help in Reaper forums of course.  Will suggest this idea also there, thought let me write it here first, where the jjazzlab boss is.  Best greetings my friend. Have a nice day, thanks for developing this fantastic tool.

**Comment by jjazzboss** [comment]
I definitely do not want to redevelop something if easier solutions exist. A better integration with a DAW such as Reaper would be really nice. But it's not clear to me how it could be done. As of today it's already possible to send JJazzLab Midi output to a DAW via a midi virtual driver (I use MidiLoop Be on Windows), but it's unidirectional, so it's only used to benefit from VST plugins sounds.
Here some possible use cases linked to enabling Midi input/editing capabilities with JJazzLab:
- Reuse JJazzLab-generated Midi tracks in a DAW project. As of today this is only possible via recording through a Midi virtual driver, or via the JJazzLab Export to Midi file feature
- Add custom tracks to JJazzLab backing tracks (a melody, record its improvisation, ...). This could be done by slaving JJazzLab to Reaper. Doable but not easy because the sequencer implementation I use does not support Midi slave sync mode. Another way is to add Midi input recording capability in JJazzLab. It's almost done actually. But it means user will also need some simple visualization/editing capabilities (via Reaper ? How can it be done in a simple way?)
- Change a rhythm pattern phrase, e.g. edit or record a new bass phrase for a given rhythm. Then the JJazzLab engine can automatically alter the pattern for any chord progression sequence.

**Comment by jjazzboss** [comment]
When I think about it, a VST JJazzLab plugin would be a good idea... You define the chord symbols + rhythm parameters in the tracks of the DAW, then the plugin uses those inputs to output Midi backing tracks. Interesting...

**Comment by michaelsjackson** [comment]
The added value of a vst would be only it would be in sync to daw timing. You could try adding midi clock slave sync to jjazzlab if you want, much easier. There are already java programs which can do this, for example Euclidean Pattern Generator 1.2, check this:
https://www.hisschemoller.com/blog/2017/euclidean-pattern-generator-1-2/
Github: https://github.com/WouterHisschemoller/Euclidean-Pattern-Generator/tree/v1.2

There are already free midi clock generating vst's, check this:
http://antonsavov.net/cms/projects/as_xc3.html

You could try both in a daw, and see how well eucliean pattern generator can be synced to it. jjazzlab could do same.  I guess this would be easiest method.

But for me syncing is not so important, when I experiment with jjazzlab I would just play its notes, the good thing is I can change at any time chords/composition in jjazzlab, but also the mixing/sounds in Reaper, optimizing both.  If all sounds interesting enough one could export .mid file, import into Reaper and there you have your sync.  The midi clock slaving would be only a nice thing to have, but we have already everything now, nothing is missing. Anything added on top would be only a bonus.

The great advantage are the available 70000 yamaha styles you can use with jjazzlab, so it is a fun field, explore some styles, create optimized track templates for selected styles, change chords, having fun. I suggested this in Reaper forums: https://forum.cockos.com/showpost.php?p=2369241&postcount=285

**Comment by jjazzboss** [comment]
Very interesting. I quickly checked the Euclidean Pattern Generator source code, it's not really slaved via midi clock sync, but you can trigger a pattern play by sending in a Midi note, EPG keeping its own Midi clock. 

> If all sounds interesting enough one could export .mid file, import into Reaper and there you have your sync.
Yes, but not super convenient if you do some trials & errors. I guess Reaper can add tracks from Midi files via drag & drop ? I could add external drag & drop feature in JJazzLab to enable this...

>... but also the mixing/sounds in Reaper, optimizing both.
If you try and face some issues, don't hesitate to ask me. E.g. I could easily add a button for this kind of "mix done outside of JJazzLab", where I switch off sending from JJazzLab instrument patch/volume/reverb/... Midi messages.

> 70000 styles
Well, you might be disappointed, there are not so many good rhythms...

**Comment by michaelsjackson** [comment]
Could be, did not try many yet, and depends probably on the requirements one has, how far out one is on the jazzy side maybe?  I am only a wanna be musician.  :-)

Outside mixing in Reaper works perfectly, the reverb settings influence anyone only yamaha xg sounds as far as I guess, so if you use any other vsti, those should not have any problematic side effects. And even if so, one could always add some filtering jsfx inbetween.  No problems here so far.

One day I should try jjazzlab with jv-1080, I guess that would sound nice as well. After april 2021 maybe.  Just for having fun, with lots of great gm sounds.

**Comment by jjazzboss** [comment]
No plans to add a piano-roll editor for now, easier to use external tools or drag&drop from/to DAWs,  like in 3.0.
