### ISSUE TITLE
Insert bars action is a bit confusing

### ISSUE THREAD

**Issue by hajdam** [jjazzboss/JJazzLab-X#9]
Insert bars action inserts on the position of the first currently selected bar, but it uses type of the bar before it for template. This is somewhat confusing as the dialog states "# bars from bar: x", but bar x - 1 is used for template.

When first bar is selected, new bar is inserted at the beginning, but it creates new section with the new name.

Maybe using first currently selected bar for template and providing also insert after or extend bar action could be more understandable...

**Comment by jjazzboss** [comment]
What do you mean by "bar x-1 is used for template" ?

Would it be more clear if dialog say "Insert 2 bars **before** bar 5" ? (instead of "Insert 2 bars from bar 5")

**Comment by jjazzboss** [comment]
Dialog now says "insert X bars **before** bar Y"

**Comment by hajdam** [comment]
Thanks and sorry I forgot to answer to your questions.
