### ISSUE TITLE
Double Click issue on mac osx

### ISSUE THREAD

**Issue by odhot** [jjazzboss/JJazzLab-X#95]
hi, i am having this issue since high sierra until mojave, i cannot double click the toolbar, and the menu folder, sometimes it can sometimes it cannot .. i hope this can be resolved

**Comment by jjazzboss** [comment]
What version are you using ? Which toolbar ? The main one or the mix console one ? All the toolbars buttons don't work ? For example you can't click on the play/stop buttons ?

**Comment by odhot** [comment]
here's the video link to show you the bugs
https://youtu.be/vUvaDqx3H5I

**Comment by jjazzboss** [comment]
Thanks odhot,  I now understand. 

Very quick answer: this is 1st time I hear about this problem. Actually the file chooser dialog is the standard java AdoptOpenJDK one (JFileChooser), not something I programmed myself. Later I'll check if it's a known bug. The fact that you have the same problem on other user interface components make me think it's probably a more general problem of the JDK, not directly of JJazzLab. I'll investigate. Could you check if you have the issue with other Java-based apps ? 

Regarding the slow scanning: I saw that several thousand of style files were scanned, that's HUGE! (the scan goes through the subdirectories as well). So this is normal it's so long. I recommend you place most of these files outside the User rhythm directory.

In a future release I'll implement a cache of the rhythm database, so it's not scanning everything on startup.

**Comment by jjazzboss** [comment]
I re-read your post. Just to make sure: you say "double-click issue" on buttons. You need to do a single click on toolbar buttons, not double-click.

**Comment by odhot** [comment]
Hi, of course i did single click on toolbar .. but it’s the same
  

  
  

  
  
>

**Comment by jjazzboss** [comment]
Could you try if you have the same issue with the software PraxisLive from www.praxislive.org ? Choose the "Experimental Windows installer with OpenJDK 11" on the download page. This software uses the same JDK and same framework than JJazzLab.

**Comment by odhot** [comment]
Ok let me try first sorry I just checked your email ;(   
  

  
  

  
  
>

**Comment by jjazzboss** [comment]
Could not reproduce
